# Generated by Django 5.0.6 on 2024-06-21 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(default='default.jpg', upload_to='profile_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcs.project')),
            ],
        ),
        migrations.CreateModel(
            name='TCS',
            fields=[
                ('testcase_id', models.AutoField(primary_key=True, serialize=False)),
                ('testcase_name', models.CharField(max_length=255)),
                ('testcase_result', models.CharField(max_length=10)),
                ('testcase_type', models.CharField(max_length=100)),
                ('testcase_description', models.TextField(blank=True, null=True)),
                ('testcase_group', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcs.file')),
            ],
        ),
    ]
